name: Validação - Lint, Testes Unitários e de Integração

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run eslint
        id: eslint
        run: npm run lint
        continue-on-error: true

      - name: Run unit tests
        id: unit
        run: npm run test:unit
        continue-on-error: true

      - name: Approve or request changes
        env:
          ESLINT: ${{ steps.eslint.outcome }}
          UNIT: ${{ steps.unit.outcome }}
        run: |
          if [[ $ESLINT == 'success' ]] && [[ $UNIT == 'success' ]]; then
            gh pr review $PR_NUMBER --approve
          else
            if [[ $ESLINT == 'failure' ]]; then
              gh pr review $PR_NUMBER --request-changes --body ":warning: Existem problemas a serem resolvidos de lint"
            fi
            if [[ $UNIT == 'failure' ]]; then
              gh pr review $PR_NUMBER --request-changes --body ":warning: Necessário corrigir os testes unitários"
            fi
          fi

      - name: Unlock or block PR
        env:
          ESLINT: ${{ steps.eslint.outcome }}
          UNIT: ${{ steps.unit.outcome }}
        run: |
          if [[ $ESLINT == 'success' ]] && [[ $UNIT == 'success' ]]; then
            gh pr unlock $PR_NUMBER
          else
            if ! gh pr lock $PR_NUMBER; then
              exit 0
            fi
          fi
